#!/bin/zsh

set -euo pipefail

prompt_file="$1"
output_file="$2"
response_file="$3"
_="${prompt_file}"

if [[ -n "${RC_MOCK_RESPONSE_FILE:-}" ]]; then
  /bin/cat "${RC_MOCK_RESPONSE_FILE}" > "${output_file}"
else
  cat > "${output_file}" <<'JSON'
{"events":[{"title":"Mock Calendar Event","start":"2026-04-01T09:00:00","end":"2026-04-01T10:00:00","allDay":false,"location":"Mock Location","notes":"Generated by the mock provider.","calendar":""}],"reason":""}
JSON
fi

printf '%s\n' "mock" > "${response_file}"
